INSERT INTO GENRES (genre_name)
VALUES ('Комедия');

INSERT INTO GENRES (genre_name)
VALUES ('Драма');

INSERT INTO GENRES (genre_name)
VALUES ('Мультфильм');

INSERT INTO GENRES (genre_name)
VALUES ('Триллер');

INSERT INTO GENRES (genre_name)
VALUES ('Документальный');

INSERT INTO GENRES (genre_name)
VALUES ('Боевик');

INSERT INTO MPA_FILM_RATING (MPA_FILM_RATING_NAME)
VALUES ('G');

INSERT INTO MPA_FILM_RATING (MPA_FILM_RATING_NAME)
VALUES ('PG');

INSERT INTO MPA_FILM_RATING (MPA_FILM_RATING_NAME)
VALUES ('PG-13');

INSERT INTO MPA_FILM_RATING (MPA_FILM_RATING_NAME)
VALUES ('R');

INSERT INTO MPA_FILM_RATING (MPA_FILM_RATING_NAME)
VALUES ('NC-17');