create table USERS
(
    ID INTEGER generated by default as identity NOT NULL primary key,
    LOGIN VARCHAR(50),
    EMAIL VARCHAR(100),
    NAME VARCHAR(50),
    BIRTHDAY DATE
);
create table MPA_FILM_RATING
(
    ID INTEGER generated by default as identity NOT NULL primary key,
    MPA_FILM_RATING_NAME VARCHAR(20)
);
create table FILMS
(
    ID INTEGER generated by default as identity NOT NULL primary key,
    NAME VARCHAR(100) NOT NULL ,
    DESCRIPTION VARCHAR(200) not null,
    RELEASE_DATE TIMESTAMP,
    DURATION INTEGER NOT NULL ,
    MPA_FILM_RATING_ID INTEGER
        references MPA_FILM_RATING(ID)
);

create table FILM_LIKES
(
    FILM_ID INTEGER
        references FILMS,
    USER_ID INTEGER
        references USERS
);
create table GENRES
(
    ID INTEGER generated by default as identity NOT NULL primary key,
    GENRE_NAME VARCHAR(50)
);
create table GENRE_FILMS
(
    FILM_ID  INTEGER
        references FILMS,
    GENRE_ID INTEGER
        references GENRES
);

create table USER_FRIENDS
(
    USER_ID   INTEGER
        references USERS,
    FRIEND_ID INTEGER
        references USERS,
    CONFIRM   BOOLEAN
);
